services:
  postgres:
    image: postgres:16
    container_name: hyu-notifier-db
    env_file:
      - ${COMPOSE_ENV_FILE:-pkg.env.production}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
